### PR TITLE
Added OpenCL info for Linux

### PR DESCRIPTION
**Pull request by thesleort**
Program used is "clinfo" from the [clinfo](https://github.com/Oblomov/clinfo) project.

It shows way more information than oclinfo, but it is a very neat and useful program. It is also very popular on Linux.

I've added a snippet of the output on my Laptop
[oclinfo.txt](https://github.com/Galarius/vscode-opencl/files/2290406/oclinfo.txt)

### CODE REVIEW

**Comment by thesleort** [comment]
Thank you for making the extension in the first place. It is very useful for my workflow!

I am not to sure what the `-pds` flag would do on `oclinfo`? However, as you mention, `clinfo` does not seem to care about that particular flag. The only other really useful flag for `clinfo` is `-l`, which returns a short list of the platforms and their devices. I've attached a snippet of that output here 
[clinfo-l.txt](https://github.com/Galarius/vscode-opencl/files/2294850/clinfo-l.txt)

The flags could probably be available in some way in the future, but at the moment I don't really find it that important.

With a little more research into vscode extensions, I might contribute or propose some more stuff in the future!

**Comment by Galarius** [comment]
`-pds` stands for "platforms & devices" ( [ocl-info](https://github.com/Galarius/ocl-info) ).

> With a little more research into vscode extensions, I might contribute or propose some more stuff in the future!

This would be great!

**Comment by thesleort** [comment]
Ahh should have done my homework! 

I did just compile it on Linux and it appears to work without any caveats? Unless you know of any problems, I could upload the compiled Linux version instead?

**Comment by Galarius** [comment]
According to [download page](https://code.visualstudio.com/Download) VS Code runs on Debian, Ubuntu, Red Hat, Fedora and SUSE. I haven't tested ocl-info on every supported operating system, so clinfo seems to be a more reliable choice.

**Pull request merged**
